### PR TITLE
fix(sheets): improve edit mode toggle

### LINKED ISSUE #203: Character sheet editing and viewing is finicky
I'm clicking around my character sheet and oops accidentally clicked on an edit box. Oops accidentally changed the name. It seems like it's always editable which is nice I am in the habit of clicking on things I read and it causes dialog box after dialog box to come up. A better design would include a toggle which will mark the sheet as read only or edit mode.

### PR DESCRIPTION
**Pull request by Fronix**
## Summary

Improves edit mode toggle for character sheets to address issue #203, where users could accidentally modify sheets by clicking on editable elements while reading.

- Change `editingEnabled` flag default from `true` to `false`, making sheets read-only by default
- Hide edit/delete/create buttons when not in edit mode via conditional rendering
- Improve visual distinction of the edit toggle button with enhanced styling (disabled state colors and transitions)
- Update components to derive `editingEnabled` state from actor flags instead of context store
- Refactor ActorConditionsList to properly use reactive actor reference

image
image

## Changes

- Character sheets are now **read-only by default**. Users must toggle edit mode to make changes.
- `editingEnabled` flag now defaults to `false` instead of `true`
- Edit/delete/create buttons are no longer visible when editing is disabled (previously shown but disabled)

---

Fixes #203

### CODE REVIEW

File: src/view/sheets/components/MovementSpeed.svelte [hunk 1]
```diff
@@ -88,9 +87,7 @@
 	}
 
 	.nimble-movement__primary {
-		display: flex;
-		align-items: baseline;
-		gap: 0.5rem;
+		margin-block-end: 0;
 	}
```
Comment (trevlar) [inline src/view/sheets/components/MovementSpeed.svelte]: This breaks the movement view when there are multiple move speeds...

Before Changes:

Image

After changes:

Image

File: src/view/sheets/PlayerCharacterSheet.svelte [hunk 2]
```diff
@@ -396,25 +396,37 @@
...
-                    --nimble-actor-image-y-offset: {actorImageYOffset}px;
-                    --nimble-actor-image-scale: {actorImageScale}%;
-                "
+					--nimble-actor-image-x-offset: {actorImageXOffset}px;
+					--nimble-actor-image-y-offset: {actorImageYOffset}px;
+					--nimble-actor-image-scale: {actorImageScale}%;
+				"
 			/>
-		</button>
+		{/if}
```
Comment (trevlar) [inline src/view/sheets/PlayerCharacterSheet.svelte]: I think it would be nice to just disable the button and use an empty tooltip/aria-label when editing is disabled. It uses specific settings on the config tab to set the image position.

**Review by trevlar — CHANGES_REQUESTED** [review]
These tab button icons on the sheet are not centered when in editing mode

Image

File: src/view/sheets/components/MovementSpeed.svelte (hunk 1 above)
Comment (Fronix) [reply src/view/sheets/components/MovementSpeed.svelte]: Oh right, it shows more than that, totally forgot, good catch!
