### PR TITLE
Fix spell upcasting bugs and add scaling editor

### LINKED ISSUE #321: Problems with the Spell Upcasting Dialog
Spell upcast descriptions are showing up on higherLevelEffect description it would be great if we had an upcast description where that is included.

The spell upcast data is not available when editing a spell or creating a new one.

Additionally Pyroclasm was showing 100 mana that could be upcast. Really we should only show the amount to upcast that the hero has available in mana.

Fiery Embrace and others can go to 0 mana which shouldn't be possible resulting in a negative mana result.

### PR DESCRIPTION
**Pull request by Fronix**
## Summary
Closes #321

- **Mana slider bugs**: Safe property access prevents the 100-mana slider (Pyroclasm) and 0-mana minimum (Fiery Embrace). NPCs without mana no longer crash the dialog.
- **Tier fallback fix**: Null/undefined `highestUnlockedSpellTier` now defaults to 9 instead of 0.
- **Separate upcast & higher level effects**: New `upcastEffect` field separates upcast descriptions (extra mana spent) from `higherLevelEffect` (character-level scaling). Both display independently in the description editor, summary, chat card, and tooltip when populated.
- **World migration**: Moves `higherLevelEffect` to `upcastEffect` on world load, but only for spells with upcast scaling configured. Spells without upcast scaling keep their higher level effect untouched.
- **Spell scaling editor**: Visual CRUD editor for scaling mode, deltas, and choice groups. Target effect uses a dropdown from activation effects with a text fallback for new spells.
- **JSON editor fallback**: Toggle between visual editor and raw JSON editing of the full spell config.
- **i18n**: All editor strings use translation keys.

## Test plan

- [ ] Open Pyroclasm (tier 4) on a character with < 100 mana — slider should cap at available mana
- [ ] Open Fiery Embrace (tier 5) — slider minimum should be 5, never 0
- [ ] Open upcast dialog as an NPC — should not crash
- [ ] Tier 1+ spell with upcast scaling — "Upcast Effect" tab appears in description editor
- [ ] Cantrip — only "Base Effect" and "Higher Level Effect" tabs, no "Upcast Effect"
- [ ] Tier 1+ spell — "Upcast" section shows in summary, chat card, and tooltip
- [ ] Add content to both fields on a tier 1+ spell — both sections display independently
- [ ] World migration only migrates spells with upcast/upcastChoice scaling mode (check console logs)
- [ ] Spells with `scaling.mode = 'none'` keep `higherLevelEffect` untouched after migration
- [ ] Scaling editor: add/edit/remove deltas and choices
- [ ] Target effect dropdown populates from activation effects; text fallback with tooltip on new spells
- [ ] JSON editor toggle works and shows full system data
- [ ] Run existing tests: `npx vitest run`

🤖 PR description generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: src/view/sheets/pages/SpellSummaryTab.svelte [hunk 1]
```diff
@@ -24,25 +26,37 @@
...
+			{/if}
+		{/await}
+	{/if}
+
+	{#if spellTier > 0 && !isUtilitySpell && upcastEffectDescription}
+		{#await foundry.applications.ux.TextEditor.implementation.enrichHTML(upcastEffectDescription) then upcastContent}
+			{#if upcastContent}
+				<section class="nimble-spell-description-content">
+					<header class="nimble-section-header">
+						<h4 class="nimble-heading" data-heading-variant="section">Upcast</h4>
```
Comment (trevlar) [inline src/view/sheets/pages/SpellSummaryTab.svelte]: More i18n

**Review by trevlar — CHANGES_REQUESTED** [review]
A few minor things.

**Comment by Fronix** [comment]
@trevlar i'll send in a small PR for the i18n for those i missed
